#!/bin/sh
set -e

# tmux new-session -d -s runbot "while true; do sh; done"
# tmux send-keys -t runbot "./main.py" C-m
# ttyd -W tmux attach-session -t runbot
#
#
python3 -m standalone_scripts.fetch_game_data
sleep 1
python3 main.py
