[project]
name = "artifactsmmo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "cachetools>=7.1.7",
  "httpx>=0.28.1",
  "python-decouple>=3.8",
  "websockets>=16.0",
]

[dependency-groups]
dev = [
  "cmaes>=0.13.0",
  "optuna>=4.9.0",
  "python-decouple-stubs>=3.8.0.4",
  { include-group = "cli" },
]
cli = [
  "prompt-toolkit>=3.0.52",
  "python-levenshtein>=0.27.3",
]
